-- =========================================================================
-- COSTLAB / SUPERBASE: SQL PATCH FOR BILL SEQUENCE & IDENTITY UNLOCK
-- Copy and paste this script into Supabase Dashboard -> SQL Editor -> Run
-- =========================================================================

-- 1. ปลดล็อกตาราง bills ให้สามารถระบุเลข ID / ลำดับบิลเริ่มต้นเองได้ (GENERATED BY DEFAULT)
ALTER TABLE public.bills ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. รีเซ็ตตัวนับ Sequence ของตาราง bills ให้เริ่มนับที่เลข 1 (หรือรันต่อจากจำนวนแถวจริง)
-- หากต้องการล้างบิลเก่าและเริ่มที่ 1:
-- DELETE FROM public.bills WHERE id > 0;
ALTER TABLE public.bills ALTER COLUMN id RESTART WITH 1;

-- 3. ปลดล็อกตาราง tasks และ works สำหรับระบบ LINE Bot
ALTER TABLE public.tasks ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.works ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 4. ตั้งค่าเริ่มต้นใน system_options ให้เป็นเลข 1
UPDATE public.system_options 
SET data = jsonb_set(
  jsonb_set(COALESCE(data, '{}'::jsonb), '{bill_start_sequence}', '1'),
  '{ลำดับบิลเริ่มต้น}', '1'
),
updated_at = timezone('utc'::text, now())
WHERE id = 'system_options';
