-- =========================================================================
-- COSTLAB / SUPERBASE: ALL-IN-ONE COMPLETE MIGRATION SCRIPT
-- Run this single script in Supabase Dashboard -> SQL Editor
-- It sets up all tables, indexes, RLS security, storage buckets, 
-- system configurations, default dropdowns, and the ADMIN account.
-- =========================================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================================================================
-- 1. TABLES DEFINITIONS
-- =========================================================================

-- 1. Projects Table (โครงการ)
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,                                      -- ID Project (e.g. 1, 2, PRJ-001)
  name TEXT NOT NULL,                                       -- ชื่อ Project
  customer_name TEXT,                                       -- ชื่อลูกค้า
  budget NUMERIC DEFAULT 0,                                 -- งบไม่เกิน
  vat_total NUMERIC DEFAULT 0,                              -- ยอดรวม vat
  color TEXT DEFAULT 'Green',                               -- สีสถานะ (Red / Green)
  company TEXT,                                             -- บริษัท
  responsible_person TEXT,                                  -- ผู้รับผิดชอบ
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Stores Table (ร้านค้า)
CREATE TABLE IF NOT EXISTS public.stores (
  id TEXT PRIMARY KEY,                                      -- id_store
  name TEXT NOT NULL,                                       -- ชื่อร้านค้า
  full_name TEXT,                                           -- ชื่อเต็ม
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  phone TEXT,                                               -- เบอร์โทร
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT                                               -- เลขที่ผู้เสียภาษี
);

-- 3. Contractors Table (รับเหมา)
CREATE TABLE IF NOT EXISTS public.contractors (
  id TEXT PRIMARY KEY,                                      -- id_Contractor
  nickname TEXT,                                            -- ชื่อเล่น
  full_name TEXT,                                           -- ชื่อ-นามสกุล
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  id_card TEXT,                                             -- บัตรประจำตัวประชาชน
  phone TEXT,                                               -- เบอร์โทรศัพท์
  address TEXT,                                             -- ที่อยู่
  annual_limit NUMERIC DEFAULT 0                            -- จำกัดยอด/ปี
);

-- 4. Contract Works Table (งานรับเหมา / เปิดจ้าง)
CREATE TABLE IF NOT EXISTS public.contract_works (
  id TEXT PRIMARY KEY,                                      -- id_Conwork (e.g. CW1, CW2)
  contractor_id TEXT REFERENCES public.contractors(id) ON DELETE SET NULL,
  project_id TEXT REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name TEXT,
  total_contract_amount NUMERIC DEFAULT 0,                  -- ยอดเงินจ้าง
  work_details TEXT,                                        -- รายละเอียดงาน
  work_date DATE,                                           -- วันที่
  phone TEXT,                                               -- เบอร์โทรศัพท์
  paid_amount NUMERIC DEFAULT 0                             -- ยอดเงินจ่าย
);

-- 5. Bills Table (กรอกบิล / เบิกเงิน)
CREATE TABLE IF NOT EXISTS public.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- ลำดับ
  project_id TEXT REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name TEXT,
  bill_type TEXT DEFAULT 'หลัก',                             -- ประเภทบิล (หลัก, ย่อย, หลัก2, ย่อย2)
  vendor_or_person TEXT,                                    -- ร้าน/บุคคล / ร้านค้า
  description TEXT,                                         -- สินค้า/ทำงาน
  bill_no TEXT,                                             -- เลขที่บิล / No.
  category TEXT,                                            -- ประเภท
  sub_category TEXT,                                        -- ประเภทหมวดย่อย
  amount NUMERIC DEFAULT 0,                                 -- ยอดเงิน / ยอดเบิก
  vat_amount NUMERIC DEFAULT 0,                             -- vat
  withholding_tax NUMERIC DEFAULT 0,                        -- หัก
  credit_days INTEGER DEFAULT 0,                            -- เครดิต
  requester TEXT,                                           -- ผู้เบิก
  bill_date DATE,                                           -- ว/ด/ป
  image_url TEXT,                                           -- รูปถ่ายบิล (Supabase Storage Public URL)
  status TEXT DEFAULT 'ตั้งเบิก',                              -- สถานะ (ตั้งเบิก, อนุมัติ, เบิกแล้ว, รอตรวจสอบ)
  approved_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tasks Table (งานทั่วไป - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,                                      -- รายการ
  do_date DATE,                                             -- ดู/ทำ
  send_date DATE,                                           -- ส่งงาน
  assignee_id TEXT,                                         -- รหัสพนักงาน
  assignee_name TEXT,                                       -- ผู้รับผิดชอบ
  status TEXT DEFAULT 'ดำเนินการ',                            -- สถานะ (ดำเนินการ / สำเร็จ)
  task_type INTEGER DEFAULT 1,                              -- ประเภทงาน (1: เอกสาร, 2: แผนงาน, 3: PJSA)
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Works Table (งาน PW / มอบหมาย - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team TEXT NOT NULL DEFAULT 'PW',                          -- ทีม (PW, PW1, PW2, PW3, PW4)
  activity_type TEXT,                                       -- กิจกรรม (เสนอราคา, ประชุมงาน, ประมูล)
  title TEXT,                                               -- เรื่อง
  pr_no TEXT,                                               -- PR
  location TEXT,                                            -- สถานที่
  date_inspect TEXT,                                        -- นัดดู
  date_propose TEXT,                                        -- นัดเสนอ
  contact1 TEXT,                                            -- ติดต่อ1
  phone1 TEXT,                                              -- เบอร์1
  contact2 TEXT,                                            -- ติดต่อ2
  phone2 TEXT,                                              -- เบอร์2
  company TEXT,                                             -- บริษัท
  status TEXT DEFAULT 'รอดูงาน',                              -- สถานะ (รอดูงาน, รอเสนอ, ส่งแล้ว, ประชุม, ฯลฯ)
  note TEXT,                                                -- หมายเหตุ
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Plans Table (แผนงาน - สำหรับ LINE Bot)
CREATE TABLE IF NOT EXISTS public.plans (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_code TEXT,                                        -- รหัสงาน
  job_name TEXT,                                            -- ชื่อแผนงาน
  item_name TEXT,                                           -- รายการ
  start_date DATE,                                          -- วันที่เริ่ม
  end_date DATE,                                            -- วันที่จบ
  days_count INTEGER DEFAULT 0,
  plan_percentage NUMERIC DEFAULT 0,
  actual_percentage NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Open',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Master Members Table (รายชื่อพนักงาน)
CREATE TABLE IF NOT EXISTS public.master_members (
  id TEXT PRIMARY KEY,                                      -- รหัสพนักงาน (e.g. admin, PT101)
  nickname TEXT,                                            -- ชื่อเล่น
  full_name TEXT,                                           -- ชื่อ-นามสกุล
  bank_name TEXT,                                           -- ชื่อธนาคาร
  bank_account TEXT,                                        -- เลขบัญชี
  phone TEXT,                                               -- เบอร์โทร
  address TEXT,                                             -- ที่อยู่
  id_card TEXT,                                             -- เลขบัตรประชาชน
  role TEXT,                                                -- สิทธิ์การใช้งาน (Admin, Manager, User)
  line_user_id TEXT,                                        -- LINE User ID
  pictureUrl TEXT                                           -- รูปโปรไฟล์
);

-- 10. Banks Table (ธนาคาร)
CREATE TABLE IF NOT EXISTS public.banks (
  id TEXT PRIMARY KEY,                                      -- id_bank (e.g. Ba101)
  name TEXT NOT NULL,                                       -- ชื่อธนาคาร
  image TEXT                                                -- โลโก้ธนาคาร
);

-- 11. Cars Table (ทะเบียนรถ)
CREATE TABLE IF NOT EXISTS public.cars (
  id TEXT PRIMARY KEY,                                      -- id_car
  plate_no TEXT NOT NULL,                                   -- หมายเลขทะเบียน
  brand TEXT,                                               -- ยี่ห้อรถ
  color TEXT,                                               -- สี
  responsible_person TEXT,                                  -- รับผิดชอบ
  owner TEXT                                                -- รถของ
);

-- 12. Categories Table (ประเภท)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name1 TEXT,
  name2 TEXT,
  name3 TEXT
);

-- 13. Customers Table (ลูกค้า)
CREATE TABLE IF NOT EXISTS public.customers (
  id TEXT PRIMARY KEY,                                      -- id_cus
  name TEXT NOT NULL,                                       -- ชื่อลูกค้า
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT                                               -- เลขที่ผู้เสียภาษี
);

-- 14. Companies Table (บริษัท)
CREATE TABLE IF NOT EXISTS public.companies (
  id TEXT PRIMARY KEY,                                      -- id_Company
  name_en TEXT,                                             -- ชื่ออังกฤษ
  name_th TEXT NOT NULL,                                    -- ชื่อบริษัท
  branch TEXT,                                              -- สำนักงาน
  address TEXT,                                             -- ที่อยู่
  tax_id TEXT,                                              -- เลขที่ผู้เสียภาษี
  phone TEXT                                                -- เบอร์โทร
);

-- 15. Loans Table (ยืมเงิน)
CREATE TABLE IF NOT EXISTS public.loans (
  id TEXT PRIMARY KEY,                                      -- id
  borrower_name TEXT,                                       -- ชื่อ
  type TEXT,                                                -- type
  amount NUMERIC DEFAULT 0,                                 -- จำนวนเงิน
  loan_date DATE                                            -- วันที่
);

-- 16. Products Table (สินค้า)
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,                                      -- id_product
  name TEXT NOT NULL,                                       -- ชื่อสินค้า
  category TEXT,                                            -- หมวดหมู่
  unit TEXT,                                                -- หน่วยนับ
  price NUMERIC DEFAULT 0,                                  -- ราคาต่อหน่วย
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 17. System Options Table (ตัวเลือกระบบ & การตั้งค่า JSONB)
CREATE TABLE IF NOT EXISTS public.system_options (
  id TEXT PRIMARY KEY DEFAULT 'system_options',
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 18. Audit Logs Table (ระบบ Log ประวัติการแก้ไข)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,                                     -- CREATE, UPDATE, DELETE
  table_name TEXT NOT NULL,
  record_id TEXT,
  changed_by TEXT,
  old_data JSONB,
  new_data JSONB,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 2. HIGH-PERFORMANCE INDEXES
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_bills_project_id ON public.bills(project_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_date ON public.bills(bill_date);
CREATE INDEX IF NOT EXISTS idx_bills_requester ON public.bills(requester);
CREATE INDEX IF NOT EXISTS idx_bills_created_at ON public.bills(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contract_works_project ON public.contract_works(project_id);
CREATE INDEX IF NOT EXISTS idx_contract_works_contractor ON public.contract_works(contractor_id);

CREATE INDEX IF NOT EXISTS idx_projects_name ON public.projects(name);
CREATE INDEX IF NOT EXISTS idx_master_members_phone ON public.master_members(phone);
CREATE INDEX IF NOT EXISTS idx_master_members_line_id ON public.master_members(line_user_id);
CREATE INDEX IF NOT EXISTS idx_system_options_id ON public.system_options(id);

-- =========================================================================
-- 3. ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- =========================================================================
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Dynamic Policy Generator (Allow full access for authenticated and anon clients)
DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'projects', 'stores', 'contractors', 'contract_works', 'bills', 
    'tasks', 'works', 'plans', 'master_members', 'banks', 'cars', 
    'categories', 'customers', 'companies', 'loans', 'products', 
    'system_options', 'audit_logs'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Public Read Access %I" ON public.%I;', t, t);
    EXECUTE format('DROP POLICY IF EXISTS "Public Write Access %I" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "Public Read Access %I" ON public.%I FOR SELECT USING (true);', t, t);
    EXECUTE format('CREATE POLICY "Public Write Access %I" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t, t);
  END LOOP;
END $$;

-- =========================================================================
-- 4. SUPABASE STORAGE BUCKETS & STORAGE RLS POLICIES
-- =========================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('bills', 'bills', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Bucket Storage RLS Policies
DROP POLICY IF EXISTS "Public Read Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access for Bills Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access for Bills Bucket" ON storage.objects;

DROP POLICY IF EXISTS "Public Read Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access for Attachments Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access for Attachments Bucket" ON storage.objects;

CREATE POLICY "Public Read Access for Bills Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'bills');
CREATE POLICY "Public Insert Access for Bills Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'bills');
CREATE POLICY "Public Update Access for Bills Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'bills');
CREATE POLICY "Public Delete Access for Bills Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'bills');

CREATE POLICY "Public Read Access for Attachments Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'attachments');
CREATE POLICY "Public Insert Access for Attachments Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'attachments');
CREATE POLICY "Public Update Access for Attachments Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'attachments');
CREATE POLICY "Public Delete Access for Attachments Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'attachments');

-- =========================================================================
-- 5. INITIAL MASTER SEED DATA (พร้อม ADMIN ACCOUNT 0800000000 / admin)
-- =========================================================================

-- 5.1 สร้าง Admin ในตารางพนักงาน (master_members)
INSERT INTO public.master_members (id, nickname, full_name, bank_account, phone, address, id_card, role)
VALUES 
  ('admin', 'Admin', 'ผู้ดูแลระบบ (Admin)', '-', '0800000000', '-', '-', 'Admin'),
  ('PT101', 'แมน', 'คุณแมน', '-', '099-999-9999', '-', '-', 'Admin'),
  ('PT102', 'ซ้อ', 'คุณซ้อ', '-', '081-888-8888', '-', '-', 'Manager'),
  ('PT103', 'การเงิน', 'บัญชี/การเงิน', '-', '081-777-7777', '-', '-', 'Manager')
ON CONFLICT (id) DO UPDATE SET 
  nickname = EXCLUDED.nickname,
  full_name = EXCLUDED.full_name,
  phone = EXCLUDED.phone,
  role = EXCLUDED.role;

-- 5.2 สร้าง User List ใน system_options (สำหรับเข้าระบบหน้าเว็บด้วยเบอร์โทร / admin)
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'users_list',
  '[
    {
      "id": "admin",
      "username": "admin",
      "displayName": "ผู้ดูแลระบบ (Admin)",
      "role": "Admin",
      "status": "Active",
      "phone": "0800000000",
      "lineUserId": "",
      "pictureUrl": "",
      "createdAt": "2026-08-22"
    },
    {
      "id": "PT101",
      "username": "PT101",
      "displayName": "คุณแมน",
      "role": "Admin",
      "status": "Active",
      "phone": "099-999-9999",
      "createdAt": "2026-01-01"
    },
    {
      "id": "PT102",
      "username": "PT102",
      "displayName": "คุณซ้อ",
      "role": "Manager",
      "status": "Active",
      "phone": "081-888-8888",
      "createdAt": "2026-01-01"
    },
    {
      "id": "PT103",
      "username": "PT103",
      "displayName": "บัญชี/การเงิน",
      "role": "Manager",
      "status": "Active",
      "phone": "081-777-7777",
      "createdAt": "2026-01-02"
    }
  ]'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = CASE 
    WHEN jsonb_typeof(system_options.data) != 'array' THEN EXCLUDED.data
    WHEN NOT (system_options.data @> '[{"username": "admin"}]'::jsonb) AND NOT (system_options.data @> '[{"id": "admin"}]'::jsonb) THEN 
      system_options.data || '[{"id": "admin", "username": "admin", "displayName": "ผู้ดูแลระบบ (Admin)", "role": "Admin", "status": "Active", "phone": "0800000000", "lineUserId": "", "pictureUrl": "", "createdAt": "2026-08-22"}]'::jsonb
    ELSE system_options.data
  END,
  updated_at = timezone('utc'::text, now());

-- 5.3 ข้อมูลการตั้งค่าระบบ (Dropdown Options)
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'system_options',
  '{
    "vat": ["รวม VAT", "ไม่รวม VAT", "ไม่มี VAT", "VAT 7%"],
    "หัก": ["ไม่มี", "หัก 1%", "หัก 3%", "หัก 5%"],
    "เครดิต": ["เงินสด", "7 วัน", "15 วัน", "30 วัน", "60 วัน"],
    "ประเภทบิล": ["หลัก", "ย่อย", "หลัก2", "ย่อย2"],
    "statusค่าแรง": ["บุคคลธรรมดา", "บริษัท"],
    "ยี่ห้อรถ": ["Toyota", "Isuzu", "Ford", "Mitsubishi", "Nissan", "Honda", "MG", "Mazda"],
    "รับผิดชอบ": ["PW1", "PW2", "PW3", "PW4", "PW"],
    "รายละเอียดงาน": [
      "งานฐานราก/เสาเข็ม",
      "งานโครงสร้าง/ผูกเหล็ก/เข้าแบบ",
      "งานเทคอนกรีต",
      "งานมุงหลังคา/กันสาด",
      "งานก่ออิฐ/ฉาบปูน",
      "งานปูกระเบื้อง/พื้น",
      "งานระบบไฟฟ้า",
      "งานระบบประปา/สุขาภิบาล",
      "งานสีและเคมี",
      "งานประตู/หน้าต่าง/กระจก",
      "งานบิวท์อิน/ตกแต่ง"
    ],
    "ชื่อเครื่องมือ": [
      "สว่านเจาะเหล็กไฟฟ้า",
      "สว่านเจาะปูน Rotary",
      "ลูกหมูขนาด 4\"",
      "ลูกหมูขนาด 7\"",
      "ไฟเบอร์ตัดเหล็ก"
    ],
    "ประเภท (ร้านค้า)": ["4.น้ำมัน", "5.ซ่อมรถ", "6.เครื่องจักร"],
    "ประเภท (ผู้รับเหมา)": ["2.ค่าแรง", "3.พนักงาน", "8.อื่นๆ"],
    "รายการประเภททั้งหมด": [
      "1.ค่าของ",
      "2.ค่าแรง",
      "3.พนักงาน",
      "4.น้ำมัน",
      "5.ซ่อมรถ",
      "6.เครื่องจักร",
      "7.เครื่องมือ",
      "8.อื่นๆ"
    ],
    "ประเภท (ร้านค้า+เลือกสินค้า)": ["1.ค่าของ", "7.เครื่องมือ", "8.อื่นๆ"],
    "PRODUCT_MASTER_DATA": [
      {"id": "1", "code": "1", "name": "ปูน/ทราย/หิน", "group": "หมวดงานโครงสร้าง", "active": true, "description": "ปูนซีเมนต์, ปูนกาว, ทรายหยาบ/ละเอียด, หิน 1-2"},
      {"id": "2", "code": "2", "name": "เหล็กเส้น/รูปพรรณ", "group": "หมวดงานโครงสร้าง", "active": true, "description": "เหล็กข้ออ้อย, เหล็กกล่อง, ไวด์แฟรงก์, ตะแกรง wiremesh"},
      {"id": "3", "code": "3", "name": "คอนกรีตผสมเสร็จ", "group": "หมวดงานโครงสร้าง", "active": true, "description": "คอนกรีต Ready-mixed 240-400 ksc"},
      {"id": "4", "code": "4", "name": "ไม้แบบ/ไม้อัด", "group": "หมวดงานโครงสร้าง", "active": true, "description": "ไม้แบบอัด, ไม้แปรรูป, ยูคล้อง"},
      {"id": "5", "code": "5", "name": "วัสดุมุง", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระเบื้องหลังคา, เมทัลชีท"},
      {"id": "6", "code": "6", "name": "ฝ้าผนัง", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "แผ่นยิปซัม, สมาร์ทบอร์ด, อิฐก่อ"},
      {"id": "7", "code": "7", "name": "ปูพื้น", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระเบื้องยาง, แกรนิตโต้, ไม้ลามิเนต"},
      {"id": "8", "code": "8", "name": "กระจก", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "กระจกอลูมิเนียม, กระจกเทมเปอร์"},
      {"id": "9", "code": "9", "name": "ไฟฟ้า", "group": "หมวดงานระบบ M&E", "active": true, "description": "สายไฟ, ตู้ควบคุม, หลอดไฟ, ท่อร้อยสาย"},
      {"id": "10", "code": "10", "name": "ประปา", "group": "หมวดงานระบบ M&E", "active": true, "description": "ท่อ PVC, ถังเก็บน้ำ, ปั๊มน้ำ"},
      {"id": "11", "code": "11", "name": "อื่นๆ(วัสดุ)", "group": "หมวดงานทั่วไป & ดำเนินการ", "active": true, "description": "วัสดุสิ้นเปลืองทั่วไป"},
      {"id": "12", "code": "12", "name": "สีเคมี", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "สีทาภายใน/นอก, เคมีภัณฑ์กันซึม"},
      {"id": "13", "code": "13", "name": "สุขภัณฑ์", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "โถส้วม, อ่างล้างหน้า, ก๊อกน้ำ"},
      {"id": "14", "code": "14", "name": "บิวอิน", "group": "หมวดงานสถาปัตยกรรม & ตกแต่ง", "active": true, "description": "เฟอร์นิเจอร์สั่งทำ, ตู้บิวท์อิน"},
      {"id": "15", "code": "15", "name": "แอร์", "group": "หมวดงานระบบ M&E", "active": true, "description": "เครื่องปรับอากาศ, ท่อน้ำยา"},
      {"id": "16", "code": "16", "name": "ดิน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ดินถม, ดินลูกรัง"},
      {"id": "17", "code": "17", "name": "หินทราย", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "หิน 1-2, ทรายหยาบ/ละเอียด"},
      {"id": "18", "code": "18", "name": "เตรียมงาน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ป้ายโครงการ, นั่งร้าน, รั้วชั่วคราว"},
      {"id": "101", "code": "101", "name": "น้ำมัน", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "น้ำมันดีเซล/เบนซิน เครื่องจักรและยานพาหนะ"},
      {"id": "102", "code": "102", "name": "ค่าขนส่ง", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ค่าขนส่งสินค้า, ค่ารถสิบล้อ"},
      {"id": "103", "code": "103", "name": "เครื่องจักร", "group": "หมวดงานเตรียมดิน & โลจิสติกส์", "active": true, "description": "ค่าเช่าแบคโฮ, เครน, เครื่องปั่นไฟ"},
      {"id": "200", "code": "200", "name": "ดำเนินการ(อื่นๆ)", "group": "หมวดงานทั่วไป & ดำเนินการ", "active": true, "description": "ค่าใช้จ่ายดำเนินงานอื่นๆ"}
    ]
  }'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = EXCLUDED.data,
  updated_at = timezone('utc'::text, now());

-- 5.4 ข้อมูลชื่อบริษัท (Company Settings)
INSERT INTO public.system_options (id, data, updated_at)
VALUES (
  'company_settings',
  '{
    "companyName": "POWERTEC",
    "companySubTitle": "ระบบบริหารและติดตามงบประมาณก่อสร้าง",
    "email": "contact@company.com",
    "phone": "02-123-4567",
    "taxId": "0105560000000",
    "address": "123/45",
    "logoUrl": ""
  }'::jsonb,
  timezone('utc'::text, now())
)
ON CONFLICT (id) DO UPDATE SET
  data = EXCLUDED.data,
  updated_at = timezone('utc'::text, now());

-- 5.5 ข้อมูลธนาคารเริ่มต้น (Default Banks)
INSERT INTO public.banks (id, name, image)
VALUES 
  ('Ba101', 'ธนาคารกสิกรไทย', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/kbank.png'),
  ('Ba102', 'ธนาคารไทยพาณิชย์', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/scb.png'),
  ('Ba103', 'ธนาคารกรุงเทพ', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/bbl.png'),
  ('Ba104', 'ธนาคารกรุงไทย', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/ktb.png'),
  ('Ba105', 'ธนาคารทหารไทยธนชาต', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/ttb.png'),
  ('Ba106', 'ธนาคารกรุงศรีอยุธยา', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/bay.png'),
  ('Ba107', 'ธนาคารออมสิน', 'https://raw.githubusercontent.com/manop/thai-banks-logo/master/gsb.png')
ON CONFLICT (id) DO NOTHING;

-- 5.6 เพิ่มคอลัมน์อัตโนมัติ (Safety Column Migrations)
ALTER TABLE public.stores ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE public.contractors ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE public.master_members ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS work_amount NUMERIC DEFAULT 0;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS start_date DATE;

-- =========================================================================
-- COMPLETION MESSAGE
-- =========================================================================
DO $$
BEGIN
  RAISE NOTICE '✅ Supabase Database Migration Completed Successfully!';
  RAISE NOTICE '👉 Admin account created: Phone "0800000000" or Username "admin" (Role: Admin)';
END $$;
